version: '3'
services:
  # Database server
  ror5sso-postgres:
    image: postgres:10.5-alpine
    ports:
      - '5432'
    volumes:
      - ror5sso-postgres-data:/var/lib/postgresql/data
    networks:
      - ror5sso
  # Nginx frontend server
  ror5sso-web:
    build:
      context: ../../
      dockerfile: docker/development/web/Dockerfile
      args:
        TIMEZONE: Europe/Moscow
        SERVER_NAME_CLIENT: ror5sso.local
        SERVER_NAME_IDP: idp.ror5sso.local
        UPSTREAM_CLIENT: ror5sso-app-client:3000
        UPSTREAM_IDP: ror5sso-app-idp:3000
    ports:
      - '80:80'
    networks:
      ror5sso:
        aliases:
          - idp.ror5sso.local
          - ror5sso.local
    depends_on:
      - ror5sso-app-client
      - ror5sso-app-idp
  # RoR client backend
  ror5sso-app-client:
    build:
      context: ../../
      dockerfile: docker/development/app/Dockerfile
      args:
        RAILS_ENV: development
        TIMEZONE: Europe/Moscow
    environment:
      DB_HOST: ror5sso-postgres
      IDP_SERVER: http://idp.ror5sso.local
      IDP_KEY: '7e47b85bce52f573323338def6dc2cb11b23d35d25a0b7732759d2a2b0a570d5'
      IDP_SECRET: '9cd06a6a4ea7adb013483e49a4c5370b0ea1e0a73dce4daacc5c0649ed2f2596'
    ports:
      - '3000'
    volumes:
      - ../../client:/var/www
      - ror5sso-client-tmp:/var/www/tmp
    networks:
      - ror5sso
    depends_on:
      - ror5sso-postgres
  # RoR idp backend
  ror5sso-app-idp:
    build:
      context: ../../
      dockerfile: docker/development/app/Dockerfile
      args:
        RAILS_ENV: development
        TIMEZONE: Europe/Moscow
    environment:
      DB_HOST: ror5sso-postgres
      IDP_CLIENT: http://ror5sso.local
      IDP_KEY: '7e47b85bce52f573323338def6dc2cb11b23d35d25a0b7732759d2a2b0a570d5'
      IDP_SECRET: '9cd06a6a4ea7adb013483e49a4c5370b0ea1e0a73dce4daacc5c0649ed2f2596'
    ports:
      - '3000'
    volumes:
      - ../../idp:/var/www
      - ror5sso-idp-tmp:/var/www/tmp
    networks:
      - ror5sso
    depends_on:
      - ror5sso-postgres

volumes:
  ror5sso-postgres-data: {}
  ror5sso-client-tmp: {}
  ror5sso-idp-tmp: {}

networks:
  ror5sso: {}
