default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>

development:
  <<: *default
  database: client_development

test:
  <<: *default
  database: client_test

production:
  <<: *default
  database: client_production
